- Rnn ke pass memory ka feature hota hai jisse vo past ka feature ko yaad kr paate hain.
- (batch_size,time-step,input-features) :--> input for RNN in tensorflow 
- Weight sharing is done in RNN while forward propagation.  

- timesteps == length of the sequence

To prepare input data for an RNN (Recurrent Neural Network) in TensorFlow, you need to shape your data appropriately. Typically, the input data for an RNN should be in the shape of [batch_size, timesteps, features]. Here's a detailed explanation of each component and a code example to illustrate the process:

Components of RNN Input:
Batch Size: The number of samples processed together in one pass through the network.
Timesteps: The number of time steps in each sample (sequence length).
Features: The number of features per time step (dimensionality of the input data).
Example Workflow:
Data Preparation:

Load your dataset.
Preprocess your data (e.g., normalization, scaling).
Create sequences and labels (for supervised learning).
Reshape Data:

Ensure your input data matches the required shape [batch_size, timesteps, features].


(batch_size, length of the sequence, no. of features) <======= input for rnn 

In [22]:
# Example Code:
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# Assume data is already loaded and preprocessed into a pandas DataFrame `df`
# For this example, let's create some dummy data
np.random.seed(42)
num_samples = 1000
timesteps = 10
features = 5

# Generate random data
data = np.random.rand(num_samples, features)
data 


array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       ...,
       [0.1531445 , 0.72811644, 0.60025141, 0.73125059, 0.76974662],
       [0.97541037, 0.57356328, 0.34164111, 0.64846456, 0.06844071],
       [0.89739732, 0.11938101, 0.32784284, 0.81574538, 0.59731238]])

In [23]:
data.shape

(1000, 5)

In [24]:
len(data)

1000

In [25]:
len(data) - timesteps

990

In [26]:
def create_sequences(data, timesteps):
    sequences = []
    labels = [] # next value in the data
    for i in range(len(data) - timesteps):
        sequences.append(data[i:i + timesteps])
        labels.append(data[i + timesteps])
    return np.array(sequences), np.array(labels)

# Create sequences and labels
X, y = create_sequences(data, timesteps)
X

array([[[3.74540119e-01, 9.50714306e-01, 7.31993942e-01, 5.98658484e-01,
         1.56018640e-01],
        [1.55994520e-01, 5.80836122e-02, 8.66176146e-01, 6.01115012e-01,
         7.08072578e-01],
        [2.05844943e-02, 9.69909852e-01, 8.32442641e-01, 2.12339111e-01,
         1.81824967e-01],
        ...,
        [8.08397348e-01, 3.04613769e-01, 9.76721140e-02, 6.84233027e-01,
         4.40152494e-01],
        [1.22038235e-01, 4.95176910e-01, 3.43885211e-02, 9.09320402e-01,
         2.58779982e-01],
        [6.62522284e-01, 3.11711076e-01, 5.20068021e-01, 5.46710279e-01,
         1.84854456e-01]],

       [[1.55994520e-01, 5.80836122e-02, 8.66176146e-01, 6.01115012e-01,
         7.08072578e-01],
        [2.05844943e-02, 9.69909852e-01, 8.32442641e-01, 2.12339111e-01,
         1.81824967e-01],
        [1.83404510e-01, 3.04242243e-01, 5.24756432e-01, 4.31945019e-01,
         2.91229140e-01],
        ...,
        [1.22038235e-01, 4.95176910e-01, 3.43885211e-02, 9.09320402e-01,
        

In [28]:
len(X)

990

In [31]:
X.shape

(990, 10, 5)

In [29]:
y

array([[0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998],
       [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451],
       ...,
       [0.1531445 , 0.72811644, 0.60025141, 0.73125059, 0.76974662],
       [0.97541037, 0.57356328, 0.34164111, 0.64846456, 0.06844071],
       [0.89739732, 0.11938101, 0.32784284, 0.81574538, 0.59731238]])

In [32]:
#  Scale features
scaler = StandardScaler()

In [33]:
X = X.reshape(-1, features) # to convert in 2-d to scale the data other wise for 3-d it gives error 
X 

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       ...,
       [0.97728382, 0.2423537 , 0.66331071, 0.8390997 , 0.55066046],
       [0.1531445 , 0.72811644, 0.60025141, 0.73125059, 0.76974662],
       [0.97541037, 0.57356328, 0.34164111, 0.64846456, 0.06844071]])

In [34]:
len(X)

9900

In [35]:
X.shape

(9900, 5)

In [38]:
X = scaler.fit_transform(X)
X

array([[-0.42000153,  1.51861954,  0.84946284,  0.35494899, -1.19410894],
       [-1.17419949, -1.49285736,  1.31970701,  0.36350691,  0.71634086],
       [-1.64149769,  1.58337974,  1.20148728, -0.99089064, -1.10480301],
       ...,
       [ 1.660059  , -0.87118358,  0.60876111,  1.19258576,  0.17159708],
       [-1.18403487,  0.76763893,  0.38776855,  0.81686657,  0.9297714 ],
       [ 1.65359373,  0.24622143, -0.51853632,  0.52846083, -1.49718302]])

In [39]:
X = X.reshape(-1, timesteps, features)
X

array([[[-0.42000153,  1.51861954,  0.84946284,  0.35494899,
         -1.19410894],
        [-1.17419949, -1.49285736,  1.31970701,  0.36350691,
          0.71634086],
        [-1.64149769,  1.58337974,  1.20148728, -0.99089064,
         -1.10480301],
        ...,
        [ 1.07723401, -0.66113616, -1.37353047,  0.65306919,
         -0.21082918],
        [-1.29138218, -0.01823143, -1.59530906,  1.43721705,
         -0.83849082],
        [ 0.5738211 , -0.63719191,  0.10676429,  0.17397449,
         -1.09431909]],

       [[-1.17419949, -1.49285736,  1.31970701,  0.36350691,
          0.71634086],
        [-1.64149769,  1.58337974,  1.20148728, -0.99089064,
         -1.10480301],
        [-1.07960798, -0.66238958,  0.12319492, -0.22583884,
         -0.72619656],
        ...,
        [-1.29138218, -0.01823143, -1.59530906,  1.43721705,
         -0.83849082],
        [ 0.5738211 , -0.63719191,  0.10676429,  0.17397449,
         -1.09431909],
        [ 1.63348918,  0.92625857,  1.57666819, 

In [41]:
len(X)

990

In [40]:
X.shape

(990, 10, 5)

In [42]:
# Split into training and testing sets
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]


In [44]:
train_size

792

In [48]:
792//32

24

In [50]:

# Define the RNN model
model = tf.keras.models.Sequential([
    tf.keras.layers.SimpleRNN(50, activation='relu', input_shape=(timesteps, features)),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Print model summary
model.summary()

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=16, validation_split=0.2)

# Make predictions
predictions = model.predict(X_test)

# Print predictions
print(predictions)

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 50)                2800      
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 2,851
Trainable params: 2,851
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
40/40 [==============================] - 1s 7ms/step - loss: 0.4266 - val_loss: 0.1762
Epoch 2/20
40/40 [==============================] - 0s 3ms/step - loss: 0.1492 - val_loss: 0.1333
Epoch 3/20
40/40 [==============================] - 0s 3ms/step - loss: 0.1192 - val_loss: 0.1201
Epoch 4/20
40/40 [==============================] - 0s 3ms/step - loss: 0.1082 - val_loss: 0.1137
Epoch 5/20
40/40 [==============================] - 0s 3

Explanation:
Data Generation:

Generate some random data to simulate a dataset with 1000 samples and 5 features.
Create Sequences:

Create sequences of a fixed length (10 timesteps) and corresponding labels.
Feature Scaling:

Normalize the features using StandardScaler to ensure the data has a mean of 0 and a standard deviation of 1.
Reshape Data:

Reshape the scaled data back to the required shape [samples, timesteps, features].
Train-Test Split:

Split the data into training and testing sets.
Model Definition:

Define a simple RNN model using SimpleRNN layer followed by a dense output layer.
Model Compilation and Training:

Compile the model with the Adam optimizer and mean squared error loss function.
Train the model on the training data.
Make Predictions:

Use the trained model to make predictions on the test data.
This code provides a basic setup for preparing and training an RNN model in TensorFlow. Adjust the parameters and model architecture based on your specific use case and dataset.